SELECT t.ORDER_ID AS SO,t.POSNR AS Item,t.MAT_CODE,p.mat_desc ,t.QTY,t.CAR_NO,t.DN_DOC,d.cust_no,d.cust_name,t.MAT_DOC,s.INVOICE_NO,s.LAST_UPD,t.PGI_MESSAGE
FROM SO_HV_DETAIL t     
LEFT JOIN
(
    SELECT DISTINCT ITEMID,CAR_NO,SO,POSNR,TO_CHAR(LAST_UPD, 'DD/MM/YYYY') AS LAST_UPD,INVOICE_NO
    FROM SO_BARCODE_DETAIL
) s ON s.CAR_NO=t.CAR_NO AND s.SO=t.ORDER_ID AND s.POSNR=t.POSNR AND s.ITEMID=t.CNT_BG_CODE
LEFT JOIN
(
     SELECT DISTINCT SO,POSNR,CUST_NO,CUST_NAME
     FROM so_detail
) d on d.so=t.order_id AND d.posnr=t.posnr
LEFT JOIN CD_MAT_INFO p ON p.MAT_CODE=t.MAT_CODE
WHERE t.DN_Doc in (
'1800041089'
)
ORDER BY t.ORDER_ID,t.POSNR,t.CAR_NO
